//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanchasGambeta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentoRoto
    {
        public int idInstrumentoRoto { get; set; }
        public int instrumento { get; set; }
        public System.DateTime fechaRotura { get; set; }
    
        public virtual Instrumento Instrumento1 { get; set; }
    }
}
