//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanchasGambeta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reserva()
        {
            this.HorarioReservas = new HashSet<HorarioReservas>();
            this.ReservaInsumos = new HashSet<ReservaInsumos>();
        }
    
        public int idReserva { get; set; }
        public int cliente { get; set; }
        public int cancha { get; set; }
        public int horario { get; set; }
        public System.DateTime fecha { get; set; }
        public bool servicioAsador { get; set; }
        public bool servicioInstrumentos { get; set; }
        public int estado { get; set; }
    
        public virtual Cancha Cancha1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioReservas> HorarioReservas { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaInsumos> ReservaInsumos { get; set; }
    }
}
